INCLUDE <P18F4321.INC>

ORG 0x100
CONFIG OSC = INTIO2
CONFIG WDT = OFF
CONFIG LVP = OFF
CONFIG BOR = OFF
BSF TRISC, TRISC1
BCF TRISC, TRISC0
BSF TRISD, TRISD1
BCF TRISD, TRISD0
BACK 
RRCF PORTC, F
BTG PORTC, 0
RRCF PORTD, F
BTG PORTD, 0
BRA BACK
END