INCLUDE <P18F4321.INC>
D0 EQU 0x30
D1 EQU 0x31
RESULT EQU 0x34
ORG 0x100
MOVLW 0x32
MOVWF STKPTR
CLRF TRISD
CLRF TRISC
SETF TRISA
MOVLW 0x01
MOVWF ADCON0
MOVLW 0x0D
MOVWF ADCON1
MOVLW 0x08
MOVWF ADCON2
START BSF ADCON0, GO
INCONV BTFSC ADCON0, DONE
BRA INCONV

MOVFF ADRESH, RESULT

CALL DIV
CALL DISPLAY
DIV CLRF D0
CLRF D1
MOVLW D'50'; Introduce maximum 2% error to allow for full range read
QUOTIENT CPFSGT RESULT
BRA DECIMAL
INCF D1, F
SUBWF RESULT, F
BRA QUOTIENT 
DECIMAL MOVLW D'5'
REMAINDER CPFSGT RESULT
BRA STOP
INCF D0, F
SUBWF RESULT, F
BRA REMAINDER
STOP RETURN

DISPLAY MOVFF D1, PORTC
MOVFF D0, PORTD
RETURN
END 